### ISSUE TITLE
[PluginUpdater] Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by SwiftExplorer567** [OakLoaf/PluginUpdater#37]
Paper 1.21.3 Server Running in Pterodactyl.

PluginUpdater / config.yml

```
check-updates-on-reload: true
allow-downloads: true

plugins:
  PluginUpdater:
    platform: modrinth
    modrinth-project-id: "IBSpJfbm"
    featured-only: false
  MWC:
    platform: modrinth
    modrinth-project-id: "3wmN97b8"
    featured-only: false
  MWP:
    platform: modrinth
    modrinth-project-id: "8VMk6P0I"
    featured-only: false
  MWI:
    platform: modrinth
    modrinth-project-id: "qvdtDX3s"
    featured-only: false
  EssentialsX:
    platform: modrinth
    modrinth-project-id: "hXiIvTyT"
    featured-only: false
  LuckPerms:
    platform: modrinth
    modrinth-project-id: "Vebnzrzj"
    featured-only: false
  ViaVersion:
    platform: modrinth
    modrinth-project-id: "P1OZGk5p"
    featured-only: false
  ViaBackwards:
    platform: modrinth
    modrinth-project-id: "NpvuJQoq"
    featured-only: false
  Floodgate:
    platform: modrinth
    modrinth-project-id: "bWrNNfkb"
    featured-only: false
  InventoryTracker:
    platform: modrinth
    modrinth-project-id: "W4nGZuFj"
    featured-only: false
  MobsToEggs:
    platform: modrinth
    modrinth-project-id: "ODULpGTh"
    featured-only: false
  AntiPopup:
    platform: modrinth
    modrinth-project-id: "HFTnFHKn"
    featured-only: false
  AdvancedBan:
    platform: spigot
    spigot-resource-id: 8695
  AntiPopup:
    platform: spigot
    spigot-resource-id: 103782
  AuraSkills:
    platform: spigot
    spigot-resource-id: 81069
  AxGraves:
    platform: spigot
    spigot-resource-id: 113629
  AxTrade:
    platform: spigot
    spigot-resource-id: 116826
  AxVaults:
    platform: spigot
    spigot-resource-id: 114764
  BetterEconomy:
    platform: spigot
    spigot-resource-id: 96690
  CMILib:
    platform: spigot
    spigot-resource-id: 87610
  ChestSort:
    platform: spigot
    spigot-resource-id: 59773
  Chunky:
    platform: spigot
    spigot-resource-id: 81534
  CrazyEnchantments:
    platform: spigot
    spigot-resource-id: 16470
  DeleteBats:
    platform: spigot
    spigot-resource-id: 10384
  EssentialsChat:
    platform: spigot
    spigot-resource-id: 9089
  EssentialsGeoIP:
    platform: spigot
    spigot-resource-id: 9089
  EssentialsSpawn:
    platform: spigot
    spigot-resource-id: 9089
  FastAsyncWorldEdit:
    platform: spigot
    spigot-resource-id: 13932
  Geyser-Spigot:
    platform: spigot
    spigot-resource-id: 81210
  HuskHomes:
    platform: spigot
    spigot-resource-id: 83767
  InvSeePlusPlus:
    platform: spigot
    spigot-resource-id: 82342
  InventoryTracker:
    platform: spigot
    spigot-resource-id: 102149
  Jobs:
    platform: spigot
    spigot-resource-id: 4216
  KeepChunks:
    platform: spigot
    spigot-resource-id: 23307
  MobsToEggs:
    platform: spigot
    spigot-resource-id: 73387
  Multiverse-Core:
    platform: spigot
    spigot-resource-id: 390
  Multiverse-Inventories:
    platform: spigot
    spigot-resource-id: 452
  Multiverse-Portals:
    platform: spigot
    spigot-resource-id: 9399
  NBTAPI:
    platform: spigot
    spigot-resource-id: 7939
  PlaceholderAPI:
    platform: spigot
    spigot-resource-id: 6245
  ProtocolLib:
    platform: spigot
    spigot-resource-id: 1997
  RoseStacker:
    platform: spigot
    spigot-resource-id: 82729
  SimpleClaimSystem:
    platform: spigot
    spigot-resource-id: 100603
  TreeAssist:
    platform: spigot
    spigot-resource-id: 67436
  Vault:
    platform: spigot
    spigot-resource-id: 34315
  VeinMiner:
    platform: spigot
    spigot-resource-id: 12038
  WildChests:
    platform: spigot
    spigot-resource-id: 69426
  WildChests:
    platform: spigot
    spigot-resource-id: 69426
  ToolStats:
    platform: modrinth
    modrinth-project-id: "oBZj9E15"
    featured-only: false

messages:
  unchecked-color: "&8"
  update-available-color: "&#ffda54"
  major-update-available-color: "&#ff6969"
  update-prepared-color: "&#ffda54"
  latest-version-color: "&#b7faa2"
  updates-available: "&#e0c01b%amount% &#ffe27aupdates are available, type &#e0c01b'%updates_command%' &#ffe27afor more information!"

```

Console:
```
[17:04:40 INFO]: SwapSkipS issued server command: /updater runchecks
[17:04:44 ERROR]: [PluginUpdater] Index 0 out of bounds for length 0
[17:04:46 INFO]: SwapSkipS issued server command: /updater unregisteredplugins
[17:04:50 ERROR]: [PluginUpdater] Index 0 out of bounds for length 0
[294.112s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 4k, detached.
[294.115s][warning][os,thread] Failed to start the native thread for java.lang.Thread "HttpClient-170-Worker-1"
[294.124s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 4k, detached.
[17:04:51 ERROR]: [PluginUpdater] unable to create native thread: possibly out of memory or process/resource limits reached
[17:04:51 ERROR]: [PluginUpdater] Failed to check if update is available for plugin 'Multiverse-Core'.
[294.125s][warning][os,thread] Failed to start the native thread for java.lang.Thread "HttpClient-171-SelectorManager"
```
